TEST:
  BATCH_SIZE: 64

OPTIM:
  METHOD: Adam
  STEPS: 1
  BETA: 0.9
  # LR: 1e-5
  LR: 0.00001
  WD: 0.

INPUT:
  # Cifar
  # SIZE: (32, 32)

  # Medical
  SIZE: [224, 224]
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 2.225]

ADAPTER:
  NAME: rotta_multilabels
  RoTTA:
    NU: 0.001
    MEMORY_SIZE: 64
    UPDATE_FREQUENCY: 64
    LAMBDA_T: 1.0
    LAMBDA_U: 1.0
    ALPHA: 0.05

LOADER:
  NUM_WORKS: 4
  SAMPLER:
    TYPE: "temporal"

# LOADER:
#   NUM_WORKS: 4

MODEL:
  ARCH: 'resnet18' # Kiến trúc mô hình > resnet18, resnet50, mobilenet_v3_small, densenet121
  NUM_CLASSES: 5 # Rất quan trọng

DATASET:
  NAME: 'CXR'
  TEST_DOMAINS: ['padchest'] # Các domain chạy TTA ['vindr', 'nih14', 'padchest']
  LABELS_LIST: ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Pleural Effusion', 'Pneumothorax']

  # VINDR_PATH: "/Users/admin/Working/Data/MixData/vinbigdata_structured"
  VINDR_PATH: "/home/ngoto/Working/Data/MixData/vinbigdata_structured"
  VINDR_CSV: "validate_reordered.csv" # "validate_reordered.csv"
  VINDR_IMAGE_DIR: "images"

  # NIH14_PATH: "/Users/admin/Working/Data/MixData/nih_14_structured"
  NIH14_PATH: "/home/ngoto/Working/Data/MixData/nih_14_structured"
  NIH14_CSV: "validate_reordered.csv" # "validate_reordered.csv"
  NIH14_IMAGE_DIR: "images"

  PADCHEST_PATH: "/Users/admin/Working/Data/MixData/PadChestPruning"
  # PADCHEST_CSV: "validate.csv"
  # PADCHEST_IMAGE_DIR: "images"
  # PADCHEST_PATH: "/home/ngo/Working/Data/MixData/PadChestPruning"
  PADCHEST_CSV: "validate_filtered.csv"
  PADCHEST_IMAGE_DIR: "images"
  
  CHEXPERT_PATH: '/Users/admin/Working/Data/MixData/nih_14_structured'
  CHEXPERT_CSV: 'validate.csv'
  CHEXPERT_IMAGE_DIR: 'valid'


  ADAPTATION_MODE: "corruption" # domain, corruption
  #Add nhieu single domain
  BASE_DOMAIN:
    # PATH: "/home/ngoto/Working/Data/CheXpert-v1.0-small"
    # CSV: "valid_split.csv" # "validate_reordered.csv, validate_reordered_subset.csv, valid_split"
    # IMAGE_DIR: "images"
    
    PATH: "/home/ngoto/Working/Data/MixData/nih_14_structured"
    CSV: "validate_reordered.csv" # "validate_reordered.csv, validate_reordered_subset.csv, valid_split"
    IMAGE_DIR: "images"

  TEST_CORRUPTIONS:
      # - 'motion_blur'
      - 'gaussian_noise'
      # - 'shot_noise'
      # - 'contrast'
      # - 'pixelate'
      # - 'jpeg_compression'
      # - 'brightness'
      # - 'gaussian_blur'

  SEVERITY: 1 # Mức độ nhiễu (0-5)