TEST:
  BATCH_SIZE: 32

OPTIM:
  METHOD: Adam
  STEPS: 1
  BETA: 0.9
  # LR: 1e-5
  LR: 0.0001
  WD: 0.

INPUT:
  # Cifar
  # SIZE: (32, 32)

  # Medical
  SIZE: [224, 224]
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 2.225]

ADAPTER:
  NAME: rotta_multilabels
  RoTTA:
    NU: 0.1
    MEMORY_SIZE: 64
    UPDATE_FREQUENCY: 64
    LAMBDA_T: 1.0
    LAMBDA_U: 1.0
    ALPHA: 0.05

LOADER:
  NUM_WORKS: 4
  SAMPLER:
    TYPE: "temporal"

# LOADER:
#   NUM_WORKS: 4

MODEL:
  ARCH: 'resnet18' # Hoặc một kiến trúc ResNet/WideResNet khác có trong robustbench
  NUM_CLASSES: 5 # Rất quan trọng

DATASET:
  NAME: 'CXR'
  TEST_DOMAINS: ['vindr', 'nih14'] # Các domain chạy TTA ['vindr', 'nih14', 'padchest']
  LABELS_LIST: ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Pleural Effusion', 'Pneumothorax']

  # VINDR_PATH: "/Users/admin/Working/Data/MixData/vinbigdata_structured"
  VINDR_PATH: "/home/ngo/Working/Data/MixData/vinbigdata_structured"
  VINDR_CSV: "validate.csv"
  VINDR_IMAGE_DIR: "images"

  # NIH14_PATH: "/Users/admin/Working/Data/MixData/nih_14_structured"
  NIH14_PATH: "/home/ngo/Working/Data/MixData/nih_14_structured"
  NIH14_CSV: "validate.csv"
  NIH14_IMAGE_DIR: "images"

  PADCHEST_PATH: "/Users/admin/Working/Data/MixData/PadChestPruning"
  # PADCHEST_CSV: "validate.csv"
  # PADCHEST_IMAGE_DIR: "images"
  # PADCHEST_PATH: "/home/ngo/Working/Data/MixData/PadChestPruning"
  PADCHEST_CSV: "validate_filtered.csv"
  PADCHEST_IMAGE_DIR: "images"
  
  CHEXPERT_PATH: '/Users/admin/Working/Data/MixData/nih_14_structured'
  CHEXPERT_CSV: 'validate.csv'
  CHEXPERT_IMAGE_DIR: 'valid'