# Đường dẫn dữ liệu
DATA:
  # CHEXPERT_PATH: "../Medical/datasets/CheXpert-v1.0-small"
  CHEXPERT_PATH: "/Users/admin/Working/Data/chexpert_pruning_U_ON"
  CHEXPERT_TRAIN_CSV: "train.csv"
  CHEXPERT_TEST_CSV: "valid.csv" # Dùng tập valid của CheXpert làm tập test

  VINDR_PATH: "../Medical/datasets/vinbigdata-chest-xray-10-percent"
  VINDR_EVAL_CSV: "train.csv"
  VINDR_IMAGE_DIR: "train" # Thư mục chứa ảnh .dicom

  CHESTXRAY14_PATH: "../Medical/datasets/nih14-10Percent"
  CHESTXRAY14_CSV: "Data_Entry_2017.csv"

  PADCHEST_PATH: "../Medical/datasets/PadChestPruning_10Percent"
  # PADCHEST_PATH: "/Users/admin/Working/Data/PadChestPruning_10Percent"
  PADCHEST_CSV: "test.csv"


COMMON_DISEASES:
    - 'Atelectasis'
    - 'Cardiomegaly'
    - 'Consolidation'
    - 'Pleural Effusion'
    - 'Pneumothorax'
    - 'No Finding'

# Cấu hình mô hình
MODEL:
  ARCH: "mobilenet_v3_small"           # Kiến trúc mô hình > resnet18, mobilenet_v3_small
  NUM_CLASSES: 6                       # Số lớp bệnh chung

# Cấu hình huấn luyện
TRAINING:
  DEVICE: "cuda"
  EPOCHS: 50
  BATCH_SIZE: 64
  LEARNING_RATE: 0.0001   # LR: Resnet 0.001  mobilenet_v3_small: 1e-5
  WEIGHT_DECAY: 1e-4
  EARLY_STOPPING_PATIENCE: 15 
  USE_WEIGHTED_LOSS: True
  USE_WEIGHTED_SAMPLER: False

OUTPUT_DIR: "./results/"