# Đường dẫn dữ liệu
DATA:
  CHEXPERT_PATH: "../Medical/datasets/CheXpert-v1.0-small"
  CHEXPERT_TRAIN_CSV: "train.csv"
  CHEXPERT_TEST_CSV: "valid.csv" # Dùng tập valid của CheXpert làm tập test

  VINDR_PATH: "../Medical/datasets/vinbigdata-chest-xray"
  VINDR_EVAL_CSV: "train.csv"
  VINDR_IMAGE_DIR: "train" # Thư mục chứa ảnh .dicom

  CHESTXRAY14_PATH: "/path/to/your/chestxray14/"
  CHESTXRAY14_CSV: "Data_Entry_2017.csv"


# Các lớp bệnh chung (giả định đã ánh xạ nhãn)
# Đây là 5 lớp phổ biến có trong cả CheXpert và VinDr-CXR
COMMON_DISEASES:
    - 'Atelectasis'
    - 'Cardiomegaly'
    - 'Consolidation'
    - 'Pleural Effusion'
    - 'Pneumothorax'
    - 'No Finding'

# Cấu hình mô hình
MODEL:
  ARCH: "resnet50"           # Kiến trúc mô hình
  NUM_CLASSES: 6             # Số lớp bệnh chung

# Cấu hình huấn luyện
TRAINING:
  DEVICE: "cuda"
  EPOCHS: 5
  BATCH_SIZE: 32
  LEARNING_RATE: 0.001

# Thư mục lưu kết quả
OUTPUT_DIR: "./results/"