DATA:
  CHEXPERT_PATH: "/Users/admin/Working/Data/chexpert_pruning_U_ON"
  CHEXPERT_TRAIN_CSV: "train.csv"
  CHEXPERT_TEST_CSV: "valid.csv"

  VINDR_PATH: "/Users/admin/Working/Data/MixData/vinbigdata_structured"
  VINDR_EVAL_CSV: "validate.csv"
  VINDR_IMAGE_DIR: "images"

  CHESTXRAY14_PATH: "/Users/admin/Working/Data/MixData/nih_14_structured"
  CHESTXRAY14_CSV: "validate.csv"
  CHESTXRAY14_IMAGE_DIR: "images"

  PADCHEST_PATH: "/Users/admin/Working/Data/MixData/PadChestPruning_structured"
  PADCHEST_CSV: "validate.csv"
  PADCHEST_IMAGE_DIR: "images"


COMMON_DISEASES:
    - 'Atelectasis'
    - 'Cardiomegaly'
    - 'Consolidation'
    - 'Pleural Effusion'
    - 'Pneumothorax'
    - 'No Finding'

# Cấu hình mô hình
MODEL:
  ARCH: "mobilenet_v3_small"           # Kiến trúc mô hình > resnet18, mobilenet_v3_small
  NUM_CLASSES: 6                       # Số lớp bệnh chung

# Cấu hình huấn luyện
TRAINING:
  DEVICE: "cuda"
  EPOCHS: 50
  BATCH_SIZE: 64
  LEARNING_RATE: 0.0001   # LR: Resnet 0.001  mobilenet_v3_small: 1e-5
  WEIGHT_DECAY: 1e-4
  EARLY_STOPPING_PATIENCE: 15 
  USE_WEIGHTED_LOSS: True
  USE_WEIGHTED_SAMPLER: False

OUTPUT_DIR: "./results/"